### ISSUE TITLE
infinite loop on lsp-sync

### ISSUE THREAD

**Issue by Delapouite** [danr/libkak#5]
Hi

I'll brain-dump the start of my investigation in this thread.

relevant content of my `kakrc` file:

```
decl str lsp_servers %{
  javascript:node ~/code/github/javascript-typescript-langserver/lib/language-server-stdio.js
}
```
when I execute `node ~/code/github/javascript-typescript-langserver/lib/language-server-stdio.js` in a shell, there's no crash, it just waits quietly. So I assume this node script works correctly.
*Edit*: it works fine with https://github.com/autozimu/LanguageClient-neovim

Then I start an empty kakoune:

```
kak -s test
```

And run a `lspc.py` in another terminal:

```
python lspc.py test -d -v
```

debug info are displayed.

Now in the running kakoune, I try to open a `js` file:

```
:e test.js
```

The hook is triggered which call `:lsp-sync`

This is where `lspyc` goes rogue, eating all my CPU:

```
…
Error deserializing server output: 
Error deserializing server output: 
Error deserializing server output: 
Error deserializing server output: 
Error deserializing server output: 
Error deserializing server output: 
Error deserializing server output: 
Error deserializing server output: 
Error deserializing server output: 
Error deserializing server output: 
Error deserializing server output: 
Error deserializing server output: 
Error deserializing server output: 
Error deserializing server output: 
Error deserializing server output: 
…
```

Which corresponds to this line https://github.com/danr/libkak/blob/13cab3925020a5c6828dc640fd043eb5fd7c9c1d/langserver.py#L109

So it appears that the `content` variable is empty and therefore not a valid JSON.

**Comment by danr** [comment]
Thanks, it should be fixed now. 

I had refactored a bit without testing the typescript langserver which actually doesn't conform to the protocol properly. Here's a bit of todo to me: 1) bug report that, 2) add some e2e tests with actual lsp servers.

**Comment by danr** [comment]
I updated sourcegraph's language server and there is another issue (from their side I think) introduced from their use of the patching library so I had to check out the parent commit, fca54b0cab ...

I will try to look into this a bit later, it takes a bit of effort to set up good testing infrastructure.

(Also it seems the `Header:  ` thing is not needed anymore (?))

**Comment by danr** [comment]
Patching bug reported at https://github.com/sourcegraph/javascript-typescript-langserver/issues/265

**Comment by danr** [comment]
Ok, this is now fixed (error was on my side, of course ;) ) so latest HEAD of the javascript-typescirpt-langserver can be used again.
